"""remove foreign key

Revision ID: 0d59831de226
Revises: bc3ed67634de
Create Date: 2024-07-08 08:57:11.726308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0d59831de226'
down_revision: Union[str, None] = 'bc3ed67634de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('articles_ibfk_1', 'articles', type_='foreignkey')
    op.drop_column('articles', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('author_id', mysql.VARCHAR(length=36), nullable=True))
    op.create_foreign_key('articles_ibfk_1', 'articles', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###
