"""type change

Revision ID: 1acda1789027
Revises: f67b4cdc1685
Create Date: 2024-06-26 08:37:36.192296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1acda1789027'
down_revision: Union[str, None] = 'f67b4cdc1685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('location_navbar', 'url',
    #            existing_type=mysql.VARCHAR(length=255),
    #            nullable=True)
    # op.alter_column('location_navbar', 'name',
    #            existing_type=mysql.VARCHAR(length=255),
    #            nullable=True)
    # op.alter_column('location_navbar', 'id',
    #            existing_type=mysql.INTEGER(),
    #            type_=sa.String(length=36),
    #            existing_nullable=False)
    # op.alter_column('main_navbar', 'url',
    #            existing_type=mysql.VARCHAR(length=255),
    #            nullable=True)
    # op.alter_column('main_navbar', 'name',
    #            existing_type=mysql.VARCHAR(length=255),
    #            nullable=True)
    # op.alter_column('main_navbar', 'id',
    #            existing_type=mysql.INTEGER(),
    #            type_=sa.String(length=36),
    #            existing_nullable=False)
    # op.alter_column('sub_navbar', 'url',
    #            existing_type=mysql.VARCHAR(length=255),
    #            nullable=True)
    # op.alter_column('sub_navbar', 'name',
    #            existing_type=mysql.VARCHAR(length=255),
    #            nullable=True)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sub_navbar', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('sub_navbar', 'url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('main_navbar', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('main_navbar', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('main_navbar', 'url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('location_navbar', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('location_navbar', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('location_navbar', 'url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
