"""index subnavbar

Revision ID: 2a6271756df6
Revises: a4831aafa3af
Create Date: 2024-07-09 10:34:52.504111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2a6271756df6'
down_revision: Union[str, None] = 'a4831aafa3af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'tag')
    op.alter_column('sub_navbar', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_sub_navbar_name'), 'sub_navbar', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sub_navbar_name'), table_name='sub_navbar')
    op.alter_column('sub_navbar', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.add_column('articles', sa.Column('tag', mysql.VARCHAR(length=36), nullable=True))
    # ### end Alembic commands ###
