"""relationship images articles

Revision ID: 3c5a53f895b9
Revises: 82310d86a5e9
Create Date: 2024-07-11 09:02:59.419371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c5a53f895b9'
down_revision: Union[str, None] = '82310d86a5e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('article_src', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'images', 'articles', ['article_src'], ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'article_src')
    # ### end Alembic commands ###
