"""type change image src

Revision ID: 43ca483123c9
Revises: 51e990e1843d
Create Date: 2024-07-11 10:15:45.671069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '43ca483123c9'
down_revision: Union[str, None] = '51e990e1843d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'authors', ['name'])
    op.alter_column('images', 'image_src',
               existing_type=mysql.VARCHAR(length=255),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'image_src',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_constraint(None, 'authors', type_='unique')
    # ### end Alembic commands ###
