"""Add published date

Revision ID: 6af5600b66c5
Revises: 929216e85eed
Create Date: 2024-07-04 15:28:31.274882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6af5600b66c5'
down_revision: Union[str, None] = '929216e85eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('published_date', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'published_date')
    # ### end Alembic commands ###
