"""relationship articles authors

Revision ID: 7454b60fdfb9
Revises: 43ca483123c9
Create Date: 2024-07-11 15:17:25.384977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7454b60fdfb9'
down_revision: Union[str, None] = '43ca483123c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('author', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'articles', 'authors', ['author'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'author')
    # ### end Alembic commands ###
