"""Add relationship column

Revision ID: bc3ed67634de
Revises: 6af5600b66c5
Create Date: 2024-07-05 13:59:55.184091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc3ed67634de'
down_revision: Union[str, None] = '6af5600b66c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('author_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'articles', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'author_id')
    # ### end Alembic commands ###
