"""unique article url

Revision ID: ecddeb5e339a
Revises: b16f4b0e26cf
Create Date: 2024-07-11 08:59:11.918739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecddeb5e339a'
down_revision: Union[str, None] = 'b16f4b0e26cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'articles', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='unique')
    # ### end Alembic commands ###
